### ISSUE TITLE
name_list [$6 awarded]

### ISSUE THREAD

**Issue by indolering** [namecoin/libcoin#10]
Implement `name_list`.
##

**Comment by domob1812** [comment]
I've started on this, but am currently having troubles to import a wallet into libcoin to test my patch.  Hopefully will be worked out soon.

**Comment by indolering** [comment]
@jonasbits has a good eye for these types of problems.

**Comment by domob1812** [comment]
This is merged now in libcoin/libcoin (including some fixes to the wallet code that were necessary to test it).  However, since there seems to be a problem with some other recent change made, the merged version crashes for me at the moment.  I'm defering to push to namecoin/libcoin until that is resolved.  I'm closing this nevertheless.

**Comment by JeremyRand** [comment]
@domob1812 This is just a reminder that there's a $6 bounty on this issue, which you should definitely claim once the code is pushed to namecoin/libcoin.

**Comment by domob1812** [comment]
Thanks for the reminer!  As you said, I'll wait until I can push a working revision to namecoin/libcoin (although the name_list patch itself works already in libcoin/libcoin).  Where do I claim the bounty, on BountySource?

**Comment by JeremyRand** [comment]
@domob1812 Yes, there should be a Claim Bounty button on BountySource.
