### ISSUE TITLE
Name Management

### ISSUE THREAD

**Issue by indolering** [namecoin/libcoin#7]
Support `name_new`, `name_firstupdate`, and `name_update`.

Should this be split into three tickets?

**Comment by JeremyRand** [comment]
Hi, the FreeSpeechMe fund will match BountySource bounties on this issue 1:1 up to $50 (so total bounty up to $100).

**Comment by JeremyRand** [comment]
The previous offer to match bounties is no longer active; I have funded a $100 bounty myself.

**Comment by vegetableman** [comment]
Would like to take a crack at this. Could you elaborate more on the issue?.

**Comment by JeremyRand** [comment]
@domob1812 Can you fill in @vegetableman on the current status of this and what exactly would be involved?

**Comment by domob1812** [comment]
I've got an untested implementation of `name_new`.  See https://github.com/domob1812/libcoin/tree/name-new, although I'm not sure if everything is there already.  Possibly not.  I got "stuck" because I ran into wallet problems when trying to test it - and then I focused on the now mostly finished Bitcoin Core rebase first.

**Comment by JeremyRand** [comment]
Closed as wontfix due to https://github.com/namecoin/libcoin/issues/20
